# Generated by Django 5.1.7 on 2025-03-28 03:58

import django.utils.timezone
import summarizer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="タイトル"
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("text", "テキスト入力"),
                            ("url", "URL入力"),
                            ("file", "ファイル入力"),
                        ],
                        max_length=10,
                        verbose_name="入力タイプ",
                    ),
                ),
                (
                    "input_content",
                    models.TextField(blank=True, verbose_name="入力内容"),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "uploaded_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=summarizer.models.upload_to_path,
                        verbose_name="アップロードファイル",
                    ),
                ),
                (
                    "original_text",
                    models.TextField(blank=True, verbose_name="元のテキスト"),
                ),
                (
                    "summary_text",
                    models.TextField(blank=True, verbose_name="要約テキスト"),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="audio/",
                        verbose_name="音声ファイル",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
            ],
            options={
                "verbose_name": "要約",
                "verbose_name_plural": "要約一覧",
                "ordering": ["-created_at"],
            },
        ),
    ]
